### ISSUE TITLE
关于检测视频流崩溃的问题。

### ISSUE THREAD

**Issue by CrazyMustard-404** [Lyric0620/ETSAuto#41]
up您好，我在检测其他视频流时，会有崩溃情况，具体触发条件不详，但对于搞分辨率视频流（1920*1080）大概率崩溃，720P视频流小概率崩溃，在调整视频窗口大小和遇到一些复杂场景（车道+道路场景复杂）时也会崩溃，请问是什么原因呢？
以下为崩溃截图和报错代码：
![Snipaste_2023-04-25_11-24-18](https://user-images.githubusercontent.com/61932303/234461193-a1659164-0c11-4e02-8493-679617941152.png)

D:\anaconda\envs\ADAS\python.exe D:/Project/Self-driving-Truck-in-Euro-Truck-Simulator2-main/script/main.py
[04/25/2023-11:16:48] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
[04/25/2023-11:16:48] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
[04/25/2023-11:16:48] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
Traceback (most recent call last):
  File "D:\anaconda\envs\ADAS\lib\site-packages\skfuzzy\control\controlsystem.py", line 586, in defuzz
    return defuzz(ups_universe, output_mf,
  File "D:\anaconda\envs\ADAS\lib\site-packages\skfuzzy\defuzzify\defuzz.py", line 248, in defuzz
    assert not zero_truth_degree, 'Total area is zero in defuzzification!'
AssertionError: Total area is zero in defuzzification!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Project/Self-driving-Truck-in-Euro-Truck-Simulator2-main/script/main.py", line 234, in <module>
    acc, ang = Follow(cipv, vertical_fuzzy, horizontal_pid, nav_line)
  File "D:\Project\Self-driving-Truck-in-Euro-Truck-Simulator2-main\Planning\Follow.py", line 17, in Follow
    acc = fuzzy_compute(vertical_fuzzy, dspeed, distance)
  File "D:\Project\Self-driving-Truck-in-Euro-Truck-Simulator2-main\Control\controllers\fuzzy_controller.py", line 108, in fuzzy_compute
    fuzzy_system.compute()
  File "D:\anaconda\envs\ADAS\lib\site-packages\skfuzzy\control\controlsystem.py", line 373, in compute
    CrispValueCalculator(consequent, self).defuzz()
  File "D:\anaconda\envs\ADAS\lib\site-packages\skfuzzy\control\controlsystem.py", line 589, in defuzz
    raise ValueError("Crisp output cannot be calculated, likely "
ValueError: Crisp output cannot be calculated, likely because the system is too sparse. Check to make sure this set of input values will activate at least one connected Term in each Antecedent via the current set of Rules.

Process finished with exit code 1

**Comment by eiyooooo** [comment]
报错参考#21 
这个项目的代码为游戏设计的，其它用法需要自行修改代码😁
