### ISSUE TITLE
Help! 安装时nvidia-index时报错

### ISSUE THREAD

**Issue by CCCCBEN** [Lyric0620/ETSAuto#53]
大佬help! nvidia-index和polygraphy安装都报错。
安装时nvidia-index时报错，提示如下：
pip install nvidia-pyindex
Collecting nvidia-pyindex 
  Using cached nvidia-pyindex-1.0.9.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done 
Building wheels for collected packages: nvidia-pyindex
  Building wheel for nvidia-pyindex (setup.py) ... error 
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      c:\program files\python39\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
       
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
     
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\nvidia_pyindex
      copying nvidia_pyindex\cmdline.py -> build\lib\nvidia_pyindex
      copying nvidia_pyindex\utils.py -> build\lib\nvidia_pyindex
      copying nvidia_pyindex\__init__.py -> build\lib\nvidia_pyindex
      running egg_info
      writing nvidia_pyindex.egg-info\PKG-INFO
      writing dependency_links to nvidia_pyindex.egg-info\dependency_links.txt
      writing entry points to nvidia_pyindex.egg-info\entry_points.txt
      writing top-level names to nvidia_pyindex.egg-info\top_level.txt
      reading manifest file 'nvidia_pyindex.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.md'
      writing manifest file 'nvidia_pyindex.egg-info\SOURCES.txt'
      c:\program files\python39\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
     
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.
     
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
     
      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      COMMAND: InstallCommand
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qxwp8kkc\nvidia-pyindex_2106c4fe88e545b0be405f66204e06b2\nvidia_pyindex\utils.py", line 20, in get_configuration_files
          output = subprocess.check_output(command, stderr=subprocess.STDOUT)
        File "c:\program files\python39\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "c:\program files\python39\lib\subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['c:\\program files\\python39\\python.exe', 'filespython39python.exe', '-c', 'from pip._internal.configuration import get_configuration_files; print(get_configuration_files())']' returned non-zero exit 
status 2.
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qxwp8kkc\nvidia-pyindex_2106c4fe88e545b0be405f66204e06b2\setup.py", line 238, in <module>
          setup(
        File "c:\program files\python39\lib\site-packages\setuptools\__init__.py", line 107, in setup 
          return distutils.core.setup(**attrs)
        File "c:\program files\python39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "c:\program files\python39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "c:\program files\python39\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "c:\program files\python39\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "c:\program files\python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "c:\program files\python39\lib\site-packages\wheel\bdist_wheel.py", line 378, in run
          self.run_command("install")
        File "c:\program files\python39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "c:\program files\python39\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "c:\program files\python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qxwp8kkc\nvidia-pyindex_2106c4fe88e545b0be405f66204e06b2\setup.py", line 172, in run
          _install_nvidia_pypi_index()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qxwp8kkc\nvidia-pyindex_2106c4fe88e545b0be405f66204e06b2\setup.py", line 71, in _install_nvidia_pypi_index
          config_filedict = get_configuration_files()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qxwp8kkc\nvidia-pyindex_2106c4fe88e545b0be405f66204e06b2\nvidia_pyindex\utils.py", line 24, in get_configuration_files
          raise RuntimeError(output) from e
      RuntimeError: c:\program files\python39\python.exe: can't open file 'C:\Users\Administrator\AppData\Local\Temp\pip-install-qxwp8kkc\nvidia-pyindex_2106c4fe88e545b0be405f66204e06b2\filespython39python.exe': [Errno 2] No such file or directory 
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nvidia-pyindex
  Running setup.py clean for nvidia-pyindex
Failed to build nvidia-pyindex
ERROR: Could not build wheels for nvidia-pyindex, which is required to install pyproject.toml-based projects

**Comment by zoeyzhuo26-lab** [comment]
me too. Have u solved this problem??
